<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  abdomen.php
 *  
 *  Created on Oct 5, 2009, 11:27:55 AM
 */

require_once MODULES_DIR . DS . 'abdomen' . DS . 'abdomen.class.inc';

if(!isset($abdomen_config)){
    $abdomen_config = new abdomenConfig();
} elseif(!$abdomen_config instanceof abdomenConfig) {
    $abdomen_config = new abdomenConfig();
}

require_once DBSTRINGS_DIR . DS . $abdomen_config->rdbms . DS . 'dbquery.php';
if(!isset($abdomen_query)){
    $abdomen_query = new dbset();
} elseif(!$abdomen_query instanceof dbset) {
    $abdomen_query = new dbset();
}

if(!isset($abdomen_exec)){
    $abdomen_exec = new abdomenModule();
} elseif(!$abdomen_exec instanceof abdomenModule) {
    $abdomen_exec = new abdomenModule();
}
