<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  eliminasi.php
 *  
 *  Created on Dec 18, 2009, 2:18:03 PM
 */

require_once MODULES_DIR . DS . 'eliminasi' . DS . 'eliminasi.class.inc';

if(!isset($eliminasi_config)){
    $eliminasi_config = new eliminasiConfig();
} elseif(!$eliminasi_config instanceof eliminasiConfig) {
    $eliminasi_config = new eliminasiConfig();
}

require_once DBSTRINGS_DIR . DS . $eliminasi_config->rdbms . DS . 'dbquery.php';
if(!isset($eliminasi_query)){
    $eliminasi_query = new dbset();
} elseif(!$eliminasi_query instanceof dbset) {
    $eliminasi_query = new dbset();
}

if(!isset($eliminasi_exec)){
    $eliminasi_exec = new eliminasiModule();
} elseif(!$eliminasi_exec instanceof eliminasiModule) {
    $eliminasi_exec = new eliminasiModule();
}
