<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  patient.php
 *  
 *  Created on Sep 27, 2009, 2:22:18 PM
 */

require_once MODULES_DIR . DS . 'patient' . DS . 'patient.class.inc';

if(!isset($patient_config)){
    $patient_config = new patientConfig();
} elseif(!$patient_config instanceof patientConfig) {
    $patient_config = new patientConfig();
}

require_once DBSTRINGS_DIR . DS . $patient_config->rdbms . DS . 'dbquery.php';
if(!isset($patient_query)){
    $patient_query = new dbset();
} elseif(!$patient_query instanceof dbset) {
    $patient_query = new dbset();
}

if(!isset($patient_exec)){
    $patient_exec = new patientModule();
} elseif(!$patient_exec instanceof patientModule) {
    $patient_exec = new patientModule();
}
