<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  diet.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'diet' . DS . 'diet.class.inc';

if(!isset($diet_config)){
    $diet_config = new dietConfig();
} elseif(!$diet_config instanceof dietConfig) {
    $diet_config = new dietConfig();
}

require_once DBSTRINGS_DIR . DS . $diet_config->rdbms . DS . 'dbquery.php';
if(!isset($diet_query)){
    $diet_query = new dbset();
} elseif(!$diet_query instanceof dbset) {
    $diet_query = new dbset();
}

if(!isset($diet_exec)){
    $diet_exec = new dietModule();
} elseif(!$diet_exec instanceof dietModule) {
    $diet_exec = new dietModule();
}
