<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  riwayat_kesehatan.php
 *  
 *  Created on Dec 17, 2009, 8:41:31 AM
 */

require_once MODULES_DIR . DS . 'riwayatKesehatan' . DS . 'riwayatKesehatan.class.inc';

if(!isset($riwayatKesehatan_config)){
    $riwayatKesehatan_config = new riwayatKesehatanConfig();
} elseif(!$riwayatKesehatan_config instanceof riwayatKesehatanConfig) {
    $riwayatKesehatan_config = new riwayatKesehatanConfig();
}

require_once DBSTRINGS_DIR . DS . $riwayatKesehatan_config->rdbms . DS . 'dbquery.php';
if(!isset($riwayatKesehatan_query)){
    $riwayatKesehatan_query = new dbset();
} elseif(!$riwayatKesehatan_query instanceof dbset) {
    $riwayatKesehatan_query = new dbset();
}

if(!isset($riwayatKesehatan_exec)){
    $riwayatKesehatan_exec = new riwayatKesehatanModule();
} elseif(!$riwayatKesehatan_exec instanceof riwayatKesehatanModule) {
    $riwayatKesehatan_exec = new riwayatKesehatanModule();
}
