<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  ekgQrs.php
 *  
 *  Created on Oct 3, 2009, 8:38:26 PM
 */

require_once MODULES_DIR . DS . 'ekgQrs' . DS . 'ekgQrs.class.inc';

if(!isset($ekgQrs_config)){
    $ekgQrs_config = new ekgQrsConfig();
} elseif(!$ekgQrs_config instanceof ekgQrsConfig) {
    $ekgQrs_config = new ekgQrsConfig();
}

require_once DBSTRINGS_DIR . DS . $ekgQrs_config->rdbms . DS . 'dbquery.php';
if(!isset($ekgQrs_query)){
    $ekgQrs_query = new dbset();
} elseif(!$ekgQrs_query instanceof dbset) {
    $ekgQrs_query = new dbset();
}

if(!isset($ekgQrs_exec)){
    $ekgQrs_exec = new ekgQrsModule();
} elseif(!$ekgQrs_exec instanceof ekgQrsModule) {
    $ekgQrs_exec = new ekgQrsModule();
}
