<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  pemberianObat.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'pemberianObat' . DS . 'pemberianObat.class.inc';

if(!isset($pemberianObat_config)){
    $pemberianObat_config = new pemberianObatConfig();
} elseif(!$pemberianObat_config instanceof pemberianObatConfig) {
    $pemberianObat_config = new pemberianObatConfig();
}

require_once DBSTRINGS_DIR . DS . $pemberianObat_config->rdbms . DS . 'dbquery.php';
if(!isset($pemberianObat_query)){
    $pemberianObat_query = new dbset();
} elseif(!$pemberianObat_query instanceof dbset) {
    $pemberianObat_query = new dbset();
}

if(!isset($pemberianObat_exec)){
    $pemberianObat_exec = new pemberianObatModule();
} elseif(!$pemberianObat_exec instanceof pemberianObatModule) {
    $pemberianObat_exec = new pemberianObatModule();
}
