<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  pemberian.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'pemberian' . DS . 'pemberian.class.inc';

if(!isset($pemberian_config)){
    $pemberian_config = new pemberianConfig();
} elseif(!$pemberian_config instanceof pemberianConfig) {
    $pemberian_config = new pemberianConfig();
}

require_once DBSTRINGS_DIR . DS . $pemberian_config->rdbms . DS . 'dbquery.php';
if(!isset($pemberian_query)){
    $pemberian_query = new dbset();
} elseif(!$pemberian_query instanceof dbset) {
    $pemberian_query = new dbset();
}

if(!isset($pemberian_exec)){
    $pemberian_exec = new pemberianModule();
} elseif(!$pemberian_exec instanceof pemberianModule) {
    $pemberian_exec = new pemberianModule();
}
