<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  keterangan.php
 *  
 *  Created on Oct 3, 2009, 8:38:26 PM
 */

require_once MODULES_DIR . DS . 'keterangan' . DS . 'keterangan.class.inc';

if(!isset($keterangan_config)){
    $keterangan_config = new keteranganConfig();
} elseif(!$keterangan_config instanceof keteranganConfig) {
    $keterangan_config = new keteranganConfig();
}

require_once DBSTRINGS_DIR . DS . $keterangan_config->rdbms . DS . 'dbquery.php';
if(!isset($keterangan_query)){
    $keterangan_query = new dbset();
} elseif(!$keterangan_query instanceof dbset) {
    $keterangan_query = new dbset();
}

if(!isset($keterangan_exec)){
    $keterangan_exec = new keteranganModule();
} elseif(!$keterangan_exec instanceof keteranganModule) {
    $keterangan_exec = new keteranganModule();
}
