<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  pemberianCairan.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'pemberianCairan' . DS . 'pemberianCairan.class.inc';

if(!isset($pemberianCairan_config)){
    $pemberianCairan_config = new pemberianCairanConfig();
} elseif(!$pemberianCairan_config instanceof pemberianCairanConfig) {
    $pemberianCairan_config = new pemberianCairanConfig();
}

require_once DBSTRINGS_DIR . DS . $pemberianCairan_config->rdbms . DS . 'dbquery.php';
if(!isset($pemberianCairan_query)){
    $pemberianCairan_query = new dbset();
} elseif(!$pemberianCairan_query instanceof dbset) {
    $pemberianCairan_query = new dbset();
}

if(!isset($pemberianCairan_exec)){
    $pemberianCairan_exec = new pemberianCairanModule();
} elseif(!$pemberianCairan_exec instanceof pemberianCairanModule) {
    $pemberianCairan_exec = new pemberianCairanModule();
}
