<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  presentStatus.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'presentStatus' . DS . 'presentStatus.class.inc';

if(!isset($presentStatus_config)){
    $presentStatus_config = new presentStatusConfig();
} elseif(!$presentStatus_config instanceof presentStatusConfig) {
    $presentStatus_config = new presentStatusConfig();
}

require_once DBSTRINGS_DIR . DS . $presentStatus_config->rdbms . DS . 'dbquery.php';
if(!isset($presentStatus_query)){
    $presentStatus_query = new dbset();
} elseif(!$presentStatus_query instanceof dbset) {
    $presentStatus_query = new dbset();
}

if(!isset($presentStatus_exec)){
    $presentStatus_exec = new presentStatusModule();
} elseif(!$presentStatus_exec instanceof presentStatusModule) {
    $presentStatus_exec = new presentStatusModule();
}
