<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  extermitas.php
 *  
 *  Created on Oct 6, 2009, 11:55:27 AM
 */


require_once MODULES_DIR . DS . 'extermitas' . DS . 'extermitas.class.inc';

if(!isset($extermitas_config)){
    $extermitas_config = new extermitasConfig();
} elseif(!$extermitas_config instanceof extermitasConfig) {
    $extermitas_config = new extermitasConfig();
}

require_once DBSTRINGS_DIR . DS . $extermitas_config->rdbms . DS . 'dbquery.php';
if(!isset($extermitas_query)){
    $extermitas_query = new dbset();
} elseif(!$extermitas_query instanceof dbset) {
    $extermitas_query = new dbset();
}

if(!isset($extermitas_exec)){
    $extermitas_exec = new extermitasModule();
} elseif(!$extermitas_exec instanceof extermitasModule) {
    $extermitas_exec = new extermitasModule();
}
