<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  vascular.php
 *  
 *  Created on Oct 1, 2009, 1:11:20 PM
 */

require_once MODULES_DIR . DS . 'vascular' . DS . 'vascular.class.inc';

if(!isset($vascular_config)){
    $vascular_config = new vascularConfig();
} elseif(!$vascular_config instanceof vascularConfig) {
    $vascular_config = new vascularConfig();
}

require_once DBSTRINGS_DIR . DS . $vascular_config->rdbms . DS . 'dbquery.php';
if(!isset($vascular_query)){
    $vascular_query = new dbset();
} elseif(!$vascular_query instanceof dbset) {
    $vascular_query = new dbset();
}

if(!isset($vascular_exec)){
    $vascular_exec = new vascularModule();
} elseif(!$vascular_exec instanceof vascularModule) {
    $vascular_exec = new vascularModule();
}
