<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  vitalSign.php
 *  
 *  Created on Oct 3, 2009, 8:38:26 PM
 */

require_once MODULES_DIR . DS . 'vitalSign' . DS . 'vitalSign.class.inc';

if(!isset($vitalSign_config)){
    $vitalSign_config = new vitalSignConfig();
} elseif(!$vitalSign_config instanceof vitalSignConfig) {
    $vitalSign_config = new vitalSignConfig();
}

require_once DBSTRINGS_DIR . DS . $vitalSign_config->rdbms . DS . 'dbquery.php';
if(!isset($vitalSign_query)){
    $vitalSign_query = new dbset();
} elseif(!$vitalSign_query instanceof dbset) {
    $vitalSign_query = new dbset();
}

if(!isset($vitalSign_exec)){
    $vitalSign_exec = new vitalSignModule();
} elseif(!$vitalSign_exec instanceof vitalSignModule) {
    $vitalSign_exec = new vitalSignModule();
}
