<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  neck.php
 *  
 *  Created on Oct 4, 2009, 8:12:20 AM
 */

require_once MODULES_DIR . DS . 'neck' . DS . 'neck.class.inc';

if(!isset($neck_config)){
    $neck_config = new neckConfig();
} elseif(!$neck_config instanceof neckConfig) {
    $neck_config = new neckConfig();
}

require_once DBSTRINGS_DIR . DS . $neck_config->rdbms . DS . 'dbquery.php';
if(!isset($neck_query)){
    $neck_query = new dbset();
} elseif(!$neck_query instanceof dbset) {
    $neck_query = new dbset();
}

if(!isset($neck_exec)){
    $neck_exec = new neckModule();
} elseif(!$neck_exec instanceof neckModule) {
    $neck_exec = new neckModule();
}
