<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  superior.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'superior' . DS . 'superior.class.inc';

if(!isset($superior_config)){
    $superior_config = new superiorConfig();
} elseif(!$superior_config instanceof superiorConfig) {
    $superior_config = new superiorConfig();
}

require_once DBSTRINGS_DIR . DS . $superior_config->rdbms . DS . 'dbquery.php';
if(!isset($superior_query)){
    $superior_query = new dbset();
} elseif(!$superior_query instanceof dbset) {
    $superior_query = new dbset();
}

if(!isset($superior_exec)){
    $superior_exec = new superiorModule();
} elseif(!$superior_exec instanceof superiorModule) {
    $superior_exec = new superiorModule();
}
