<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  perkembangan.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'perkembangan' . DS . 'perkembangan.class.inc';

if(!isset($perkembangan_config)){
    $perkembangan_config = new perkembanganConfig();
} elseif(!$perkembangan_config instanceof perkembanganConfig) {
    $perkembangan_config = new perkembanganConfig();
}

require_once DBSTRINGS_DIR . DS . $perkembangan_config->rdbms . DS . 'dbquery.php';
if(!isset($perkembangan_query)){
    $perkembangan_query = new dbset();
} elseif(!$perkembangan_query instanceof dbset) {
    $perkembangan_query = new dbset();
}

if(!isset($perkembangan_exec)){
    $perkembangan_exec = new perkembanganModule();
} elseif(!$perkembangan_exec instanceof perkembanganModule) {
    $perkembangan_exec = new perkembanganModule();
}
