<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  user.php
 *  
 *  Created on Sep 8, 2009, 9:28:36 PM
 */

require_once MODULES_DIR . DS . 'user' . DS . 'user.class.inc';

if(!isset($user_config)){
    $user_config = new userConfig();
} elseif(!$user_config instanceof userConfig) {
    $user_config = new userConfig();
}

require_once DBSTRINGS_DIR . DS . $user_config->rdbms . DS . 'dbquery.php';
if(!isset($user_query)){
    $user_query = new dbset();
} elseif(!$user_query instanceof dbset) {
    $user_query = new dbset();
}

if(!isset($user_exec)){
    $user_exec = new userModule();
} elseif(!$user_exec instanceof userModule) {
    $user_exec = new userModule();
}
