<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  kesimpulan.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'kesimpulan' . DS . 'kesimpulan.class.inc';

if(!isset($kesimpulan_config)){
    $kesimpulan_config = new kesimpulanConfig();
} elseif(!$kesimpulan_config instanceof kesimpulanConfig) {
    $kesimpulan_config = new kesimpulanConfig();
}

require_once DBSTRINGS_DIR . DS . $kesimpulan_config->rdbms . DS . 'dbquery.php';
if(!isset($kesimpulan_query)){
    $kesimpulan_query = new dbset();
} elseif(!$kesimpulan_query instanceof dbset) {
    $kesimpulan_query = new dbset();
}

if(!isset($kesimpulan_exec)){
    $kesimpulan_exec = new kesimpulanModule();
} elseif(!$kesimpulan_exec instanceof kesimpulanModule) {
    $kesimpulan_exec = new kesimpulanModule();
}
