<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  istirahat.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'istirahat' . DS . 'istirahat.class.inc';

if(!isset($istirahat_config)){
    $istirahat_config = new istirahatConfig();
} elseif(!$istirahat_config instanceof istirahatConfig) {
    $istirahat_config = new istirahatConfig();
}

require_once DBSTRINGS_DIR . DS . $istirahat_config->rdbms . DS . 'dbquery.php';
if(!isset($istirahat_query)){
    $istirahat_query = new dbset();
} elseif(!$istirahat_query instanceof dbset) {
    $istirahat_query = new dbset();
}

if(!isset($istirahat_exec)){
    $istirahat_exec = new istirahatModule();
} elseif(!$istirahat_exec instanceof istirahatModule) {
    $istirahat_exec = new istirahatModule();
}
