<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  bagian.php
 *  
 *  Created on Nov 23, 2009, 10:01:26 AM
 */

require_once MODULES_DIR . DS . 'bagian' . DS . 'bagian.class.inc';

if(!isset($bagian_config)){
    $bagian_config = new bagianConfig();
} elseif(!$bagian_config instanceof bagianConfig) {
    $bagian_config = new bagianConfig();
}

require_once DBSTRINGS_DIR . DS . $bagian_config->rdbms . DS . 'dbquery.php';
if(!isset($bagian_query)){
    $bagian_query = new dbset();
} elseif(!$bagian_query instanceof dbset) {
    $bagian_query = new dbset();
}

if(!isset($bagian_exec)){
    $bagian_exec = new bagianModule();
} elseif(!$bagian_exec instanceof bagianModule) {
    $bagian_exec = new bagianModule();
}
