<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  perawatan.php
 *  
 *  Created on Oct 1, 2009, 1:11:20 PM
 */

require_once MODULES_DIR . DS . 'perawatan' . DS . 'perawatan.class.inc';

if(!isset($perawatan_config)){
    $perawatan_config = new perawatanConfig();
} elseif(!$perawatan_config instanceof perawatanConfig) {
    $perawatan_config = new perawatanConfig();
}

require_once DBSTRINGS_DIR . DS . $perawatan_config->rdbms . DS . 'dbquery.php';
if(!isset($perawatan_query)){
    $perawatan_query = new dbset();
} elseif(!$perawatan_query instanceof dbset) {
    $perawatan_query = new dbset();
}

if(!isset($perawatan_exec)){
    $perawatan_exec = new perawatanModule();
} elseif(!$perawatan_exec instanceof perawatanModule) {
    $perawatan_exec = new perawatanModule();
}
