<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  ear.php
 *  
 *  Created on Oct 4, 2009, 7:02:13 AM
 */

require_once MODULES_DIR . DS . 'ear' . DS . 'ear.class.inc';

if(!isset($ear_config)){
    $ear_config = new earConfig();
} elseif(!$ear_config instanceof earConfig) {
    $ear_config = new earConfig();
}

require_once DBSTRINGS_DIR . DS . $ear_config->rdbms . DS . 'dbquery.php';
if(!isset($ear_query)){
    $ear_query = new dbset();
} elseif(!$ear_query instanceof dbset) {
    $ear_query = new dbset();
}

if(!isset($ear_exec)){
    $ear_exec = new earModule();
} elseif(!$ear_exec instanceof earModule) {
    $ear_exec = new earModule();
}
