<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  dictionary.php
 *  
 *  Created on Dec 19, 2009, 8:52:20 PM
 */

require_once MODULES_DIR . DS . 'dictionary' . DS . 'dictionary.class.inc';

if(!isset($dictionary_config)){
    $dictionary_config = new dictionaryConfig();
} elseif(!$dictionary_config instanceof dictionaryConfig) {
    $dictionary_config = new dictionaryConfig();
}

require_once DBSTRINGS_DIR . DS . $dictionary_config->rdbms . DS . 'dbquery.php';
if(!isset($dictionary_query)){
    $dictionary_query = new dbset();
} elseif(!$dictionary_query instanceof dbset) {
    $dictionary_query = new dbset();
}

if(!isset($dictionary_exec)){
    $dictionary_exec = new dictionaryModule();
} elseif(!$dictionary_exec instanceof dictionaryModule) {
    $dictionary_exec = new dictionaryModule();
}
