<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  inferior.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'inferior' . DS . 'inferior.class.inc';

if(!isset($inferior_config)){
    $inferior_config = new inferiorConfig();
} elseif(!$inferior_config instanceof inferiorConfig) {
    $inferior_config = new inferiorConfig();
}

require_once DBSTRINGS_DIR . DS . $inferior_config->rdbms . DS . 'dbquery.php';
if(!isset($inferior_query)){
    $inferior_query = new dbset();
} elseif(!$inferior_query instanceof dbset) {
    $inferior_query = new dbset();
}

if(!isset($inferior_exec)){
    $inferior_exec = new inferiorModule();
} elseif(!$inferior_exec instanceof inferiorModule) {
    $inferior_exec = new inferiorModule();
}
