<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  video.php
 *  
 *  Created on Oct 3, 2009, 8:38:26 PM
 */

require_once MODULES_DIR . DS . 'video' . DS . 'video.class.inc';

if(!isset($video_config)){
    $video_config = new videoConfig();
} elseif(!$video_config instanceof videoConfig) {
    $video_config = new videoConfig();
}

require_once DBSTRINGS_DIR . DS . $video_config->rdbms . DS . 'dbquery.php';
if(!isset($video_query)){
    $video_query = new dbset();
} elseif(!$video_query instanceof dbset) {
    $video_query = new dbset();
}

if(!isset($video_exec)){
    $video_exec = new videoModule();
} elseif(!$video_exec instanceof videoModule) {
    $video_exec = new videoModule();
}
