<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  pemeriksaan.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'pemeriksaan' . DS . 'pemeriksaan.class.inc';

if(!isset($pemeriksaan_config)){
    $pemeriksaan_config = new pemeriksaanConfig();
} elseif(!$pemeriksaan_config instanceof pemeriksaanConfig) {
    $pemeriksaan_config = new pemeriksaanConfig();
}

require_once DBSTRINGS_DIR . DS . $pemeriksaan_config->rdbms . DS . 'dbquery.php';
if(!isset($pemeriksaan_query)){
    $pemeriksaan_query = new dbset();
} elseif(!$pemeriksaan_query instanceof dbset) {
    $pemeriksaan_query = new dbset();
}

if(!isset($pemeriksaan_exec)){
    $pemeriksaan_exec = new pemeriksaanModule();
} elseif(!$pemeriksaan_exec instanceof pemeriksaanModule) {
    $pemeriksaan_exec = new pemeriksaanModule();
}
