<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  cardio.php
 *  
 *  Created on Oct 1, 2009, 1:11:20 PM
 */

require_once MODULES_DIR . DS . 'vasculararteri' . DS . 'vasculararteri.class.inc';

if(!isset($vasculararteri_config)){
    $vasculararteri_config = new vasculararteriConfig();
} elseif(!$vasculararteri_config instanceof vasculararteriConfig) {
    $vasculararteri_config = new vasculararteriConfig();
}

require_once DBSTRINGS_DIR . DS . $vasculararteri_config->rdbms . DS . 'dbquery.php';
if(!isset($vasculararteri_query)){
    $vasculararteri_query = new dbset();
} elseif(!$vasculararteri_query instanceof dbset) {
    $vasculararteri_query = new dbset();
}

if(!isset($vasculararteri_exec)){
    $vasculararteri_exec = new vasculararteriModule();
} elseif(!$vasculararteri_exec instanceof vasculararteriModule) {
    $vasculararteri_exec = new vasculararteriModule();
}
