<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  auth.module
 *  
 *  Created on Sep 8, 2009, 9:28:36 PM
 */

require_once MODULES_DIR . DS . 'auth' . DS . 'auth.class.inc';

if(!isset($auth_config)){
    $auth_config = new authConfig();
} elseif(!$auth_config instanceof authConfig) {
    $auth_config = new authConfig();
}

require_once DBSTRINGS_DIR . DS . $auth_config->rdbms . DS . 'dbquery.php';
if(!isset($auth_query)){
    $auth_query = new dbset();
} elseif(!$auth_query instanceof dbset) {
    $auth_query = new dbset();
}

if(!isset($auth_exec)){
    $auth_exec = new authModule();
} elseif(!$auth_exec instanceof authModule) {
    $auth_exec = new authModule();
}
