<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  pengkajian.php
 *  
 *  Created on Oct 3, 2009, 4:34:16 PM
 */

require_once MODULES_DIR . DS . 'pengkajian' . DS . 'pengkajian.class.inc';

if(!isset($pengkajian_config)){
    $pengkajian_config = new pengkajianConfig();
} elseif(!$pengkajian_config instanceof pengkajianConfig) {
    $pengkajian_config = new pengkajianConfig();
}

require_once DBSTRINGS_DIR . DS . $pengkajian_config->rdbms . DS . 'dbquery.php';
if(!isset($pengkajian_query)){
    $pengkajian_query = new dbset();
} elseif(!$pengkajian_query instanceof dbset) {
    $pengkajian_query = new dbset();
}

if(!isset($pengkajian_exec)){
    $pengkajian_exec = new pengkajianModule();
} elseif(!$pengkajian_exec instanceof pengkajianModule) {
    $pengkajian_exec = new pengkajianModule();
}
