<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  treadmill.php
 *  
 *  Created on Oct 1, 2009, 1:11:20 PM
 */

require_once MODULES_DIR . DS . 'treadmill' . DS . 'treadmill.class.inc';

if(!isset($treadmill_config)){
    $treadmill_config = new treadmillConfig();
} elseif(!$treadmill_config instanceof treadmillConfig) {
    $treadmill_config = new treadmillConfig();
}

require_once DBSTRINGS_DIR . DS . $treadmill_config->rdbms . DS . 'dbquery.php';
if(!isset($treadmill_query)){
    $treadmill_query = new dbset();
} elseif(!$treadmill_query instanceof dbset) {
    $treadmill_query = new dbset();
}

if(!isset($treadmill_exec)){
    $treadmill_exec = new treadmillModule();
} elseif(!$treadmill_exec instanceof treadmillModule) {
    $treadmill_exec = new treadmillModule();
}
