strkey	indonesia
a	A
ab	AB
abdomen_auscultation	Auscultation
abdomen_auscultation drop	Drop auscultation
abdomen_auscultation edit	Editauscultation
abdomen_auscultation form	Formulir Auscultation
abdomen_center	Center
abdomen_center drop	Drop
abdomen_center edit	Edit
abdomen_center form	Form
abdomen_gerakan_dinding_perut	Gerakan dinding perut
abdomen_gerakan_dinding_perut drop	Drop
abdomen_gerakan_dinding_perut edit	Edit
abdomen_gerakan_dinding_perut form	Form
abdomen_ginjal	Ginjal
abdomen_ginjal drop	Drop
abdomen_ginjal edit	Edit
abdomen_ginjal form	Form
abdomen_hepar	Hepar
abdomen_hepar drop	Drop
abdomen_hepar edit	Edit
abdomen_hepar form	Form
abdomen_inspeksi_ginjal	Inspeksi Ginjal
abdomen_inspeksi_ginjal drop	Drop
abdomen_inspeksi_ginjal edit	Edit
abdomen_inspeksi_ginjal form	Formulir
abdomen_liver	Liver
abdomen_liver drop	Drop
abdomen_liver edit	Edit
abdomen_liver form	Formulir
abdomen_peristaltik_usus	Peristaltik Usus
abdomen_peristaltik_usus drop	Drop
abdomen_peristaltik_usus edit	Edit
abdomen_peristaltik_usus form	Formulir
abdomen_perkusi	Perkusi
abdomen_perkusi drop	Drop
abdomen_perkusi edit	Edit
abdomen_perkusi form	Formulir
abdomen_relief	Relief
abdomen_relief drop	Drop
abdomen_relief edit	Edit
abdomen_relief form	Formulir
abdomen_skin	Kulit
abdomen_skin drop	Drop
abdomen_skin edit	Edit
abdomen_skin form	Formulir
add group	Grup
add user	Tambah pengguna
administer	Pengaturan admin
af	AF
af reference detail for holterref	Detil referensi AF untuk holterref
af reference form for holterref	Formulir referensi AF untuk holterref
agama	Agama
alamat	Alamat
alergi	Alergi
all menu thats used by administrator to manage entire system configurations	Semua menu yang digunakan oleh administrator untuk mengatur konfigurasi sistem secara keseluruhan
all menu thats used by user to manage their entry and self configurations	Semua menu yang digunakan pengguna untuk mengatur inputan mereka dan juga konfigurasinya sendiri
antrian pasien	Antrian Pasien
antrian pasien rawat inap	Antrian pasien rawat inap
antrian pasien yang mendaftar pada hari ini	Antrian pasien yang mendaftar pada hari ini
anusrectum_inspections	Inspeksi
anusrectum_inspections drop	Drop
anusrectum_inspections edit	Edit
anusrectum_inspections form	Formulir
anusrectum_rectal_touche	Rectal Touche
anusrectum_rectal_touche drop	Drop
anusrectum_rectal_touche edit	Edit
anusrectum_rectal_touche form	Formulir
asuransi	Asuransi
auscultation reference detail for abdomen	Detil referensi auscultation untuk abdomen
auscultation reference form for abdomen	Formulir referensi auscultation untuk ebdomen
auscultation_kind reference detail for hearth	Detil referensi jenis auscultation untuk jantung
auscultation_kind reference form for hearth	Formulir referensi jenis auscultation untuk jantung
auscultation_quality reference detail for hearth	Detil referensi kualitas untuk jantung
auscultation_quality reference form for hearth	Formulir referensi untuk jantung
auscultation_sound reference detail for hearth	Detil referensi untuk jantung
auscultation_sound reference form for hearth	Formulir referensi untuk jantung
axis	Axis
axis reference detail for ekgqrs	Detil referensi untuk EKG QRS
axis reference form for ekgqrs	Formulir referensi untuk EKG QRS
b	B
bagian	Bagian
bagian drop	Hapus Bagian
bagian edit	Edit
bagian form submit	Formulir Submit
bahasa	Bahasa
bali	Bali
banten	Banten
bengkulu	Bengkulu
berat	Berat
budha	Budha
bunyi_pernafasan reference detail for punggung	Detil referensi untuk punggung
bunyi_pernafasan reference form for punggung	Formulir referensi untuk punggung
bunyi_tambahan reference detail for punggung	Detil referensi bunyi tambahan untuk punggung
bunyi_tambahan reference form for punggung	Formulir referensi bunyi tambahan
cara_bayar	Cara Bayar
cara_berkunjung	Cara Berkunjung
cardio anak	cardio anak
cardio dewasa	Cardio dewasa
cardio message	Pesan
cari data pasien	Cari data pasien
cari pasien	Cari pasien
cari pasien rawat inap	Cari pasien rawat inap
center reference detail for abdomen	Detil referensi center
center reference form for abdomen	Formulir referensi center
cerai	Cerai
change password	Ganti sandi
choose	Pilih
clear	Bersihkan
clear all dumped words that not translated yet	Bersihkan semua kalimat tersaring yang belum diterjemahkan
clear dump	Bersihkan dump
cornea	Kornea
cornea reference detail for eye	Detil referensi kornea
cornea reference form for eye	Formulir referensi kornea
daerah istimewa yogyakarta	Daerah Istimewa Yogyakarta
daerah khusus ibukota jakarta	Daerah Khusus Ibukota Jakarta
daftar alergi	Daftar Alergi
daftar bagian	Daftar bagian
daftar bahasa	Daftar bahasa
daftar bahasa yang terdaftar dalam system ini	Daftar bahasa yang terdaftar dalam sistem ini
daftar bahasa yang tersedia	Daftar bahasa yang tersedia
daftar pasien	Daftar pasien
daftar pasien rawat inap	Daftar pasien rawat inap
daftar pasien yang mendaftar hari ini	Daftar pasien yang mendaftar hari ini
daftar pengkajian	Daftar pengkajian
daftar rencana perawatan	Daftar rencana perawatan
daftar riwayat kesehatan	Daftar riwayat kesehatan
default	Default
default-smarty	Default-smarty
delete group	Hapus grup
delete user	Hapus pengguna
denyut_jantung reference detail for fekg	Detil referensi denyut jantung
denyut_jantung reference form for fekg	Formulir referensi denyut jantung
depresi	Depresi
depresi reference detail for ekgst	Detil referensi depresi
depresi reference form for ekgst	Formulir referensi depresi
detail bagian	Detil bagian
detail cardio anak	Detil cardio anak
detail cardio anak's patients	Detil pasien cardio anak
detail cardio dewasa	Detil cardio dewasa
detail cardio dewasa's patients	Detil pasien cardio dewasa
detail ekg	Detil EKG
detail ekg's patients	Detil pasien EKG
detail form alergi	Detil formulir alergi
detail form rencana	Formulir detil rencana
detail form riwayatkesehatan	Formulir detil riwayat kesehatan
detail holter	Detil holter
detail holter's patients	Detil pasien holter
detail information of language translation	Informasi detil penerjemahan bahasa
detail pasien	Detil pasien
detail perawatan	Detil perawatan
detail perawatan's patients	Detil pasien perawatan
detail treadmill	Detil treadmill
detail treadmill's patients	Detil pasien treadmill
detail vascular	Detil vascular
detail vascular's patients	Detil pasien vascular
detil abdomen_auscultation	Detil abdomen auscultation
detil abdomen_center	Detil abdomen center
detil abdomen_gerakan_dinding_perut	Detil abdomen gerakan dinding perut
detil abdomen_ginjal	Detil abdomen ginjal
detil abdomen_hepar	Detil abdomen hepar
detil abdomen_inspeksi_ginjal	Detil abdomen inspeksi ginjal
detil abdomen_liver	Detil abdomen liver
detil abdomen_peristaltik_usus	Detil abdomen peristaltik usus
detil abdomen_perkusi	Detil abdomen perkusi
detil abdomen_relief	Detil abdomen relief
detil abdomen_skin	Detil abdomen kulit
detil anusrectum_inspections	Detil inspeksi anusrectum
detil anusrectum_rectal_touche	Detil rectal touche
detil axis fase latihan	Detil fase latihan axis
detil denyut_jantung	Detil denyut jantung
detil depresi fase latihan	Detil depresi fase latihan
detil dihentikan fase latihan	Detil dihentikan
detil durasi	Detil durasi
detil ekspresi	Detil ekspresi
detil extermitas_inspections	Detil inspeksi extermitas
detil gelombang p	Detil gelombang P
detil heartblock qrs complex	Detil heartblock QRS Complex
detil hearth_auscultation_kind	Detil jenis auscultation
detil hearth_auscultation_quality	Detil kualitas auscultation
detil hearth_auscultation_sound	Detil auscultation suara
detil hearth_inspection	Detil inspeksi jantung
detil hearth_intencity	Detil intensitas
detil hearth_localization	Detil lokalisasi
detil hearth_palpation	Detil palpasi
detil hearth_penjalaran	Detil penjalaran
detil hearth_percussion_bottom	Detil perkusi bawah
detil hearth_percussion_left	Detil perkusi kiri
detil hearth_percussion_right	Detil perkusi kanan
detil hearth_percussion_top	Detil perkusi atas
detil irama dasar	Detil irama dasar
detil keluhan	Detil keluhan
detil klasifikasi fungsional	Detil klasifikasi fungsional
detil konfigurasi	Detil konfigurasi
detil perubahan gelombang r	Detil perubahan gelombang R
detil protokol fase latihan	Detil protokol fase latihan
detil punggung_bunyi_pernafasan	Detil bunyi pernafasan
detil punggung_bunyi_tambahan	Detil bunyi tambahan
detil punggung_inspections	Detil inspeksi punggung
detil punggung_others	Detil lainnya
detil punggung_palpations	Detil palpasi
detil q_interval fekg	Detil Q interval
detil rambut	Detil rambut
detil respon tekanan darah	Detil respon tekanan darah
detil respon_jantung fase latihan	Detil respon jantung
detil rlbs qrs complex	Detil ribs QRS colmpeks
detil svt fase latihan	Detil SVT
detil tingkat kesegaran jasmani	Detil tingkat kesegaran jasmani
detil tipe tanda vital	Detil tipe tanda vital
detil ves	Detil VES
dictionary	Kamus
dihentikan	dihentikan
dihentikan reference detail for faselatihan	Detil referensi dihentikan
dihentikan reference form for faselatihan	Formulir referensi dihentikan
dokter	Dokter
durasi	Durasi
durasi reference detail for ekgqrs	Detil referensi durasi
durasi reference detail for ekgst	Detil referensi durasi
durasi reference form for ekgqrs	Formulir referensi durasi
durasi reference form for ekgst	Formulir referensi durasi
echocardiography check form	Formulir pemeriksaan echocardiography
echocardiography form	Formulir echocardiography
echocardiography form submit	Formulir submit echocardiography
echocardiography message	Pesan echocardiography
editing  risk_factor reference form for present status	Formulir edit referensi faktor resiko
editing af reference form for holterref	Formulir edit referensi AF
editing auscultation reference form for abdomen	Formulir edit referensi auscultation
editing auscultation_kind reference form for hearth	Formulir edit referensi jenis auscultation
editing auscultation_quality reference form for hearth	Formulir edit referensi kualitas auscultation
editing auscultation_sound reference form for hearth	Formulir edit referensi suara auscultation
editing axis reference form for ekgqrs	Formulir edit referensi axis
editing bagian reference form	Formulir edit referensi bagian
editing bunyi_pernafasan reference form for punggung	Formulir edit referensi bunyi pernafasan
editing bunyi_tambahan reference form for punggung	Formulir edit bunyi tambahan
editing center reference form for abdomen	Formulir edit referensi center
editing cornea reference form for eye	Formulir edit referensi kornea
editing denyut_jantung reference form for fekg	Formulir edit referensi denyut jantung
editing depresi reference form for ekgst	Formulir edit referensi depresi
editing dihentikan reference form for faselatihan	Formulir edit referensi dihentikan
editing durasi reference form for ekgqrs	Formulir edit referensi durasi
editing durasi reference form for ekgst	Formulir edit referensi durasi
editing expression reference form for headface	Formulir edit referensi ekspresi
editing fungsional reference form for threadkesimpulansaran	Formulir edit referensi fungsional
editing gelombang p reference form for fekg	Formulir edit referensi gelombang P
editing gerakan_dinding_perut reference form for abdomen	Formulir edit referensi gerakan dinding perut
editing ginjal reference form for abdomen	Formulir edit referensi ginjal
editing hair reference form for headface	Formulir edit referensi rambut
editing heartblock reference form for holterref	Formulir edit referensi heartblock
editing hepar reference form for abdomen	Formulir edit referensi hati
editing illness_history reference form for present status	Formulir edit referensi riwayat penyakit
editing inspection reference form for hearth	Formulir edit referensi inspeksi
editing inspections reference form for anusrectum	Formulir edit referensi inspeksi
editing inspections reference form for extermitas	Formulir edit referensi inspeksi
editing inspections reference form for eye	Formulir edit referensi inspeksi
editing inspections reference form for headface	Formulir edit referensi inspeksi
editing inspections reference form for punggung	Formulir edit referensi inspeksi
editing inspeksi_ginjal reference form for abdomen	Formulir edit referensi inspeksi
editing intencity reference form for hearth	Formulir edit referensi intensiti
editing irama reference form for fekg	Formulir edit referensi irama
editing kelopak_mata reference form for eye	Formulir edit referensi kelopak mata
editing kesadaran reference form for vitalsign	Formulir edit referensi kesadaran
editing kesegaran reference form for threadkesimpulansaran	Formulir edit referensi kesegaran
editing konfig_rekaman reference form for faselatihan	Formulir edit referensi konfig rekaman
editing konjunctifa reference form for eye	Formulir edit referensi konjuctifa
editing liver reference form for abdomen	Formulir edit referensi liver
editing localization reference form for hearth	Formulir edit referensi lokalisasi
editing nutrient reference form for present status	Formulir edit referensi nutrisi
editing others reference form for punggung	Formulir edit referensi lainnya
editing palpation reference form for hearth	Formulir edit referensi palpasi
editing palpations reference form for punggung	Formulir edit referensi palpasi
editing penjalaran reference form for hearth	Formulir edit referensi penjalaran
editing percussion_bottom reference form for hearth	Formulir edit referensi perkusi bawah
editing percussion_left reference form for hearth	Formulir edit referensi perkusi kiri
editing percussion_right reference form for hearth	Formulir edit referensi perkusi kanan
editing percussion_top reference form for hearth	Formulir edit referensi perkusi atas
editing peristaltik_usus reference form for abdomen	Formulir edit referensi peristaltik usus
editing perkusi reference form for abdomen	Formulir edit referensi perkusi
editing perubahan_gelombang reference form for faselatihan	Formulir edit referensi perubahan gelombang
editing protokol reference form for faselatihan	Formulir edit referensi protokol
editing pulse_rythm reference form for vitalsign	Formulir edit referensi ritme pulsa
editing pupil reference form for eye	Formulir edit referensi pupil
editing qpatologi reference form for ekgqrs	Formulir edit referensi Qpatologi
editing qpatologi reference form for ekgst	Formulir edit referensi Qpatologi
editing q_interval reference form for fekg	Formulir edit referensi Q interval
editing rectal_touche reference form for anusrectum	Formulir edit referensi rectal touche
editing relief reference form for abdomen	Formulir edit referensi relief
editing respon_jantung reference form for faselatihan	Formulir edit referensi respon jantung
editing respon_jantung reference form for fekg	Formulir edit referensi respon jantung
editing rlbs reference form for ekgqrs	Formulir edit referensi iga
editing rlbs reference form for ekgst	Formulir edit referensi iga
editing skin reference form for abdomen	Formulir edit referensi kulit
editing soreness reference form for present status	Formulir edit referensi nyeri
editing svt reference form for holterref	Formulir edit referensi SVT
editing tekanandarah reference form for threadkesimpulansaran	Formulir edit referensi tekanan darah
editing tekanan_bola_mata reference form for eye	Formulir edit referensi tekanan bola mata
editing type reference form for vitalsign	Formulir edit referensi tipe
editing ulib reference form for threadkesimpulansaran	Formulir edit referensi ULJB
editing ves reference form for holterref	Formulir edit referensi VAS
ekg	EKG
ekg lists	Daftar EKG
ekg message	Pesan EKG
ekgqrs_axis drop	Hapus QRS Axis
ekgqrs_axis edit	Edit QRS Axis
ekgqrs_axis form	Formulir QRS Axis
ekgqrs_durasi drop	Hapus QRS Durasi
ekgqrs_durasi edit	Edit Durasi
ekgqrs_durasi form	Formulir durasi
ekgqrs_qpatologi drop	Hapus QPatologi
ekgqrs_qpatologi edit	Edit QPatologi
ekgqrs_qpatologi form	Formulir QPatologi
ekgqrs_rlbs drop	Hapus Iga
ekgqrs_rlbs edit	Edit Iga
ekgqrs_rlbs form	Formulir Iga
ekgst_depresi drop	Hapus depresi
ekgst_depresi edit	Edit depresi
ekgst_depresi form	Formulir depresi
ekgst_durasi drop	Hapus durasi
ekgst_durasi edit	Edit durasi
ekgst_durasi form	Formulir durasi
ekgst_qpatologi drop	Hapus QPatologi
ekgst_qpatologi edit	Edit QPatologi
ekgst_qpatologi form	Formulir QPatologi
ekgst_rlbs drop	Hapus Iga
ekgst_rlbs edit	Edit Iga
ekgst_rlbs form	Formulir Iga
eksekusi formulir pendaftaran group	Eksekusi formulir pendaftaran grup
eksekusi formulir pendaftaran pengguna	Eksekusi formulir pendaftaran pengguna
eksekusi perintah delete groups	Eksekusi perintah hapus grup
eksekusi perintah delete users	Eksekusi perintah hapus pengguna
eksekusi perintah edit untuk tabel groups	Eksekusi perintah edit tabel grup
eksekusi perintah edit untuk tabel users	eksekusi perintah edit tabel pengguna
eksekusi perubahan informasi pengguna	Eksekusi perubahan informasi pengguna
eksekusi perubahan sandi pengguna	Eksekusi perubahan sandi pengguna
eksekusi registrasi pendaftaran pasien rawat inap	Eksekusi registrasi pendaftaran pasien rawat inap
ekspresi	Ekspresi
execute af reference form for holterref	Eksekusi formulir referensi AF
execute auscultation reference form for abdomen	Eksekusi formulir referensi auscultation
execute auscultation_kind reference form for hearth	Eksekusi formulir referensi auscultation
execute auscultation_quality reference form for hearth	Eksekusi formulir referensi kualitas auscultation
execute auscultation_sound reference form for hearth	Eksekusi formulir referensi suara auscultation
execute axis reference form for ekgqrs	Eksekusi formulir referensi axis
execute bagian reference form	Eksekusi formulir referensi bagian
execute bunyi_pernafasan reference form for punggung	Eksekusi formulir referensi bunyi pernafasan
execute bunyi_tambahan reference form for punggung	Eksekusi formulir referensi bunyi tambahan
execute center reference form for abdomen	Eksekusi formulir referensi center
execute cornea reference form for eye	Eksekusi formulir referensi kornea
execute denyut_jantung reference form for fekg	Eksekusi formulir referensi denyut jantung
execute depresi reference form for ekgst	Eksekusi formulir referensi depresi
execute dihentikan reference form for faselatihan	Eksekusi formulir referensi dihentikan
execute durasi reference form for ekgqrs	Eksekusi formulir referensi durasi
execute durasi reference form for ekgst	Eksekusi formulir referensi durasi
execute echocardiography check form	Eksekusi formulir pemeriksaan echocardiography
execute expression reference form for headface	Eksekusi formulir referensi ekspresi
execute fungsional reference form for threadkesimpulansaran	Eksekusi formulir referensi fungsional
execute gelombang p reference form for fekg	Eksekusi formulir referensi gelombang P
execute gerakan_dinding_perut reference form for abdomen	Eksekusi formulir referensi gerakan dinding perut
execute ginjal reference form for abdomen	Eksekusi formulir referensi ginjal
execute hair reference form for headface	Eksekusi formulir referensi rambut
execute heartblock reference form for holterref	Eksekusi formulir referensi heartblock
execute hepar reference form for abdomen	Eksekusi formulir referensi hati
execute illness_history reference form for present status	Eksekusi formulir referensi riwayat penyakit
execute inspection reference form for hearth	Eksekusi formulir referensi inspeksi
execute inspections reference form for anusrectum	Eksekusi formulir referensi inspeksi
execute inspections reference form for extermitas	Eksekusi formulir referensi inspeksi
execute inspections reference form for eye	Eksekusi formulir referensi inspeksi
execute inspections reference form for headface	Eksekusi formulir referensi inspeksi
execute inspections reference form for punggung	Eksekusi formulir referensi inspeksi
execute inspeksi_ginjal reference form for abdomen	Eksekusi formulir referensi inspeksi ginjal
execute intencity reference form for hearth	Eksekusi formulir referensi intensiti
execute irama reference form for fekg	Eksekusi formulir referensi irama
execute kelopak_mata reference form for eye	Eksekusi formulir referensi kelopak mata
execute kesadaran reference form for vitalsign	Eksekusi formulir referensi kesadaran
execute kesegaran reference form for threadkesimpulansaran	Eksekusi formulir referensi kesegaran
execute konfig_rekaman reference form for faselatihan	Eksekusi formulir referensi konfig rekaman
execute konjunctifa reference form for eye	Eksekusi formulir referensi konjunctifa
execute liver reference form for abdomen	Eksekusi formulir referensi liver
execute localization reference form for hearth	Eksekusi formulir referensi lokalisasi
execute nutrient reference form for present status	Eksekusi formulir referensi nutrisi
execute others reference form for punggung	Eksekusi formulir referensi lainnya
execute palpation reference form for hearth	Eksekusi formulir referensi palpasi
execute palpations reference form for punggung	Eksekusi formulir referensi palpasi
execute penjalaran reference form for hearth	Eksekusi formulir referensi penjalaran
execute percussion_bottom reference form for hearth	Eksekusi formulir referensi perkusi bawah
execute percussion_left reference form for hearth	Eksekusi formulir referensi perkusi kiri
execute percussion_right reference form for hearth	Eksekusi formulir referensi perkusi kanan
execute percussion_top reference form for hearth	Eksekusi formulir referensi perkusi atas
execute peristaltik_usus reference form for abdomen	Eksekusi formulir referensi peristaltik usus
execute perkusi reference form for abdomen	Eksekusi formulir referensi perkusi
execute perubahan_gelombang reference form for faselatihan	Eksekusi formulir referensi perubahan gelombang
execute protokol reference form for faselatihan	Eksekusi formulir referensi protokol
execute pulse_rythm reference form for vitalsign	Eksekusi formulir referensi ritme pulsa
execute pupil reference form for eye	Eksekusi formulir referensi pupil
execute qpatologi reference form for ekgqrs	Eksekusi formulir referensi QPatologi
execute qpatologi reference form for ekgst	Eksekusi formulir referensi QPatologi
execute q_interval reference form for fekg	Eksekusi formulir referensi Q interval
execute rectal_touche reference form for anusrectum	Eksekusi formulir referensi rectal touche
execute registering patient into database	Eksekusi register pasien ke dalam database
execute relief reference form for abdomen	Eksekusi formulir referensi relif
execute respon_jantung reference form for faselatihan	Eksekusi formulir referensi respon jantung
execute respon_jantung reference form for fekg	Eksekusi formulir referensi respon jantung
execute risk_factor reference form for present status	Eksekusi formulir referensi faktor resiko
execute rlbs reference form for ekgqrs	Eksekusi formulir referensi iga
execute rlbs reference form for ekgst	Eksekusi formulir referensi iga
execute skin reference form for abdomen	Eksekusi formulir referensi kulit
execute soreness reference form for present status	Eksekusi formulir referensi nyeri
execute svt reference form for holterref	Eksekusi formulir referensi SVT
execute tekanandarah reference form for threadkesimpulansaran	Eksekusi formulir referensi tekanan darah
execute tekanan_bola_mata reference form for eye	Eksekusi formulir referensi tekanan bola mata
execute type reference form for vitalsign	Eksekusi formulir referensi tipe
execute ulib reference form for threadkesimpulansaran	Eksekusi formulir referensi ULJB
execute ves reference form for holterref	Eksekusi formulir referensi VES
explore cardio anak	eksplore cardio anak
explore cardio dewasa	Eksplor cardio dewasa
explore ekg	Eksplor EKG
explore holter	Eksplor holter
explore treadmill	Eksplor treadmill
explore vascular	Eksplor vascular
expression reference detail for headface	Detil referensi ekspresi
expression reference form for headface	Formulir referensi ekspresi
extermitas_inspections	Inspeksi extermitas
extermitas_inspections drop	Hapus inspeksi
extermitas_inspections edit	Edit inspeksi
extermitas_inspections form	Formulir inspeksi
eye_cornea drop	Hapus kornea
eye_cornea edit	Edit kornea
eye_cornea form	Formulir kornea
eye_inspections drop	Hapus inspeksi
eye_inspections edit	Edit inspeksi
eye_inspections form	Formulir inspeksi
eye_kelopak_mata drop	Hapus kelopak mata
eye_kelopak_mata edit	Edit kelopak mata
eye_kelopak_mata form	Formulir kelopak mata
eye_konjunctifa drop	Hapus konjunctifa
eye_konjunctifa edit	Edit konjunctifa
eye_konjunctifa form	Formulir konjunctifa
eye_pupil drop	Hapus pupil
eye_pupil edit	Edit pupil
eye_pupil form	Formulir pupil
eye_tekanan_bola_mata drop	Hapus bola mata
eye_tekanan_bola_mata edit	Edit tekanan bola mata
eye_tekanan_bola_mata form	Formulir tekanan bola mata
faktor resiko	Faktor resiko
faselatihan_dihentikan drop	Hapus dihentikan
faselatihan_dihentikan edit	Edit dihentikan
faselatihan_dihentikan form	Formulir dihentikan
faselatihan_konfig_rekaman drop	Hapus konfig rekaman
faselatihan_konfig_rekaman edit	Edit konfig rekaman
faselatihan_konfig_rekaman form	Formulir konfig rekaman
faselatihan_perubahan_gelombang drop	Hapus perubahan gelombang
faselatihan_perubahan_gelombang edit	Edit perubahan gelombang
faselatihan_perubahan_gelombang form	Formulir perubahan gelombang
faselatihan_protokol drop	Hapus protokol
faselatihan_protokol edit	Edit protokol
faselatihan_protokol form	Formulir protokol
faselatihan_respon_jantung drop	Hapus respon jantung
faselatihan_respon_jantung edit	Edit respon jantung
faselatihan_respon_jantung form	Formulir respon jantung
fekg denyut jantung	Denyut jantung
fekg gelombang p	Gelombang P
fekg irama dasar	Irama dasar
fekg_denyut_jantung drop	Hapus denyut jantung
fekg_denyut_jantung edit	Edit denyut jantung
fekg_denyut_jantung form	Formulir denyut jantung
fekg_gelombang p drop	Hapus gelombang P
fekg_gelombang p edit	Edit gelombang P
fekg_gelombang p form	Formulir gelombang P
fekg_irama drop	Hapus irama
fekg_irama edit	Edit irama
fekg_irama form	Formulir irama
fekg_q_interval drop	Hapus Q interval
fekg_q_interval edit	Edit Q interval
fekg_q_interval form	Formulir Q interval
fekg_respon_jantung drop	Hapus respon jantung
fekg_respon_jantung edit	Edit respon jantung
fekg_respon_jantung form	Formulir respon jantung
form alergi	Alergi
form cardio anak	Formulir cardio anak
form cardio dewasa	Formulir cardio dewasa
form ekg	Formulir EKG
form fekg	Formulir FEKG
form for fekg	Formulir untuk FEKG
form holter	Formulir holter
form holter submit	Holter submit
form holter today list	Daftar holter hari ini
form rencana	Formulir rencana
form riwayatkesehatan	Formulir riwayat kesehatan
form to manipulate language	Formulir untuk memanipulasi bahasa
form treadmill	Formulir treadmill
form vascular	Formulir vascular
formulir alergi pasien	Formulir alergi pasien
formulir cardio anak	Formulir cardio anak
formulir cardio dewasa	Formulir cardio dewasa
formulir detil alergi pasien	Formulir detil alergi pasien
formulir detil rencana pasien	Formulir detil rencana pasien
formulir detil riwayatkesehatan pasien	Formulir detil riwayat kesehatan pasien
formulir ekg	Formulir EKG
formulir holter	Formulir holter
formulir input bagian	Formulir input bagian
formulir pendaftaran group	Formulir pendaftaran grup
formulir pendaftaran pasien	Formulir pendaftaran pasien
formulir pendaftaran pengguna	Formulir pendaftaran pengguna
formulir rencana pasien	Formulir rencana pasien
formulir riwayatkesehatan pasien	Formulir riwayat kesehatan pasien
formulir treadmill	Formulir treadmill
formulir vascular	Formulir vascular
fungsional reference detail for threadkesimpulansaran	Detil referensi fungsional
fungsional reference form for threadkesimpulansaran	Formulir referensi fungsional
gelombang p reference detail for fekg	Detil referensi gelombang P
gelombang p reference form for fekg	Formulir referensi gelombang P
general information service for accessed by public	Layanan informasi umum untuk diakses publik
gerakan_dinding_perut reference detail for abdomen	Detil referensi gerakan dinding perut
gerakan_dinding_perut reference form for abdomen	Formulir referensi gerakan dinding perut
get cardio message	Pesan cardio
get echocardiography message	Pesan echocardiography
get ekg lists	Daftar EKG
get ekg message	Pesan EKG
get holter message	Pesan holter
get patient detail info	Informasi detil pasien
get perawatan message	Pesan perawatan
get strnum	Nomor register
get treadmillmessage	Pesan treadmill
get vascularmessage	Pesan vascular
ginjal reference detail for abdomen	Detil referensi ginjal
ginjal reference form for abdomen	Formulir referensi ginjal
gizi	Gizi
gol_darah	Golongan Darah
gorontalo	Gorontalo
group	Grup
group detail	Detil grup
group edit	Edit grup
hair reference detail for headface	Detil referensi rambut
hair reference form for headface	Formulir referensi rambut
headface_expression drop	Hapus ekspresi kepala dan muka
headface_expression edit	Edit ekspresi kepala dan muka
headface_expression form	Formulir ekspresi kepala dan muka
headface_hair drop	Hapus rambut
headface_hair edit	Edit rambut
headface_hair form	Formulir rambut
headface_inspections drop	Hapus inspeksi
headface_inspections edit	Edit inspeksi
headface_inspections form	Formulir inspeksi
heartblock	Heartblock
heartblock reference detail for holterref	Detil referensi heartblock
heartblock reference form for holterref	Formulir referensi heartblock
hearth_auscultation_kind	Jenis auscultation
hearth_auscultation_kind drop	Hapus jenis auscultation
hearth_auscultation_kind edit	Edit jenis auscultation
hearth_auscultation_kind form	Formulir jenis auscultation
hearth_auscultation_quality	Kualitas auscultation
hearth_auscultation_quality drop	Hapus kualitas auscultation
hearth_auscultation_quality edit	Edit kualitas auscultation
hearth_auscultation_quality form	Formulir kualitas auscultation
hearth_auscultation_sound	Suara auscultation
hearth_auscultation_sound drop	Hapus suara
hearth_auscultation_sound edit	Edit auscultation suara
hearth_auscultation_sound form	Formulir auscultation suara
hearth_inspection	Inspeksi jantung
hearth_inspection drop	Hapus inspeksi
hearth_inspection edit	Hapus inspeksi
hearth_inspection form	Formulir inspeksi
hearth_intencity	Intensitas
hearth_intencity drop	Hapus intensitas
hearth_intencity edit	Edit intensitas
hearth_intencity form	Formulir intensitas
hearth_localization	Lokalisasi
hearth_localization drop	Hapus lokalisasi
hearth_localization edit	Edit lokalisasi
hearth_localization form	Formulir lokalisasi
hearth_palpation	Palpasi
hearth_palpation drop	Hapus palpasi
hearth_palpation edit	Edit palpasi
hearth_palpation form	Formulir palpasi
hearth_penjalaran	Penjalaran
hearth_penjalaran drop	Hapus penjalaran
hearth_penjalaran edit	Edit penjalaran
hearth_penjalaran form	Formulir penjalaran
hearth_percussion_bottom	Perkusi bawah
hearth_percussion_bottom drop	Hapus perkusi bawah
hearth_percussion_bottom edit	Edit perkusi bawah
hearth_percussion_bottom form	Formulir perkusi bawah
hearth_percussion_left	Perkusi kiri
hearth_percussion_left drop	Hapus perkusi kiri
hearth_percussion_left edit	Edit perkusi kiri
hearth_percussion_left form	Formulir perkusi kiri
hearth_percussion_right	Perkusi kanan
hearth_percussion_right drop	Hapus perkusi kanan
hearth_percussion_right edit	Edit perkusi kanan
hearth_percussion_right form	Formulir perkusi kanan
hearth_percussion_top	Perkusi atas
hearth_percussion_top drop	Hapus perkusi atas
hearth_percussion_top edit	Edit perkusi atas
hearth_percussion_top form	Formulir perkusi atas
hepar reference detail for abdomen	Detil referensi hati
hepar reference form for abdomen	Formulir referensi hati
hindu	Hindu
holter	Holter
holter message	Pesan holter
holterref_af drop	Hapus AF
holterref_af edit	Edit AF
holterref_af form	Formulir AF
holterref_heartblock drop	Hapus heartblock
holterref_heartblock edit	Edit heartblock
holterref_heartblock form	Formulir heartblock
holterref_svt drop	Hapus SVT
holterref_svt edit	Edit SVT
holterref_svt form	Formulir SVT
holterref_ves drop	Hapus VES
holterref_ves edit	Edit VES
holterref_ves form	Formulir VES
id	ID
illness_history drop	Hapus riwayat penyakit
illness_history edit	Edit riwayat penyakit
illness_history form	Formulir riwayat penyakit
illness_history reference detail for present status	Detil referensi riwayat penyakit
illness_history reference form for present status	Formulir referensi riwayat penyakit
in	dalam
indikasi	Indikasi
indonesia	Indonesia
informasi detail pasien	Informasi detil pasien
inspection reference detail for hearth	Detil referensi inspeksi
inspection reference form for hearth	Fromulir referensi inspeksi
inspections reference detail for anusrectum	Detil referensi inspeksi
inspections reference detail for extermitas	Detil referensi inspeksi
inspections reference detail for eye	Detil referensi inspeksi
inspections reference detail for headface	Detil referensi inspeksi
inspections reference detail for punggung	Detil referensi inspeksi
inspections reference form for anusrectum	Formulir referensi inspeksi
inspections reference form for extermitas	Formulir referensi inspeksi
inspections reference form for eye	Formulir referensi inspeksi
inspections reference form for headface	Formulir referensi inspeksi
inspections reference form for punggung	Formulir referensi inspeksi
inspeksi kepala & muka	Inspeksi kepala dan muka
inspeksi mata	Inspeksi mata
inspeksi_ginjal reference detail for abdomen	Detil referensi inspeksi ginjal
inspeksi_ginjal reference form for abdomen	Formulir referensi inspeksi ginjal
intencity reference detail for hearth	Detil referensi intensitas
intencity reference form for hearth	Formulir referensi intensitas
irama nadi	Irama nadi
irama reference detail for fekg	Detil referensi irama
irama reference form for fekg	Formulir referensi irama
is amount	sebanyak
islam	Islam
jambi	Jambi
jawa barat	Jawa Barat
jawa tengah	Jawa tengah
jawa timur	Jawa timur
jumlah kata	Jumlah kata
kabupaten bantaeng	Kabupaten Bantaeng
kabupaten barru	Kabupaten Barru
kabupaten bone	Kabupaten Bone
kabupaten bulukumba	Kabupaten Bulukumba
kabupaten enrekang	Kabupaten Enrekang
kabupaten gowa	Kabupaten Gowa
kabupaten jeneponto	Kabupaten Jeneponto
kabupaten kepulauan selayar	Kabupaten Kepulauan Selayar
kabupaten luwu	Kabupaten Luwu
kabupaten luwu timur	Kabupaten Luwu Timur
kabupaten luwu utara	Kabupaten Luwu Utara
kabupaten maros	Kabupaten Maros
kabupaten pangkajene dan kepul	Kabupaten Pangkajene Kepulauan
kabupaten pinrang	Kabupaten Pinrang
kabupaten sidenreng rappang	Kabupaten Sidenreng Rappang
kabupaten sinjai	Kabupaten Sinjai
kabupaten soppeng	Kabupaten Soppeng
kabupaten takalar	Kabupaten Takalar
kabupaten tana toraja	Kabupaten Tana Toraja
kabupaten toraja utara	Kabupaten Toraja Utara
kabupaten wajo	Kabupaten Wajo
kalimantan barat	Kalimantan Barat
kalimantan selatan	Kalimantan Selatan
kalimantan tengah	Kalimantan Tengah
kalimantan timur	Kalimantan Timur
kawin	Kawin
kelamin	Kelamin
kelopak mata	Kelopak mata
kelopak_mata reference detail for eye	Detil referensi kelopak mata
kelopak_mata reference form for eye	Formulir referensi kelopak mata
keluhan	Keluhan
keluhan utama	Keluhan utama
kepulauan bangka belitung	Kepulauan Bangka Belitung
kepulauan riau	Kepulauan Riau
kesadaran	Kesadaran
kesadaran reference detail for vitalsign	Detil referensi kesadaran
kesadaran reference form for vitalsign	Formulir referensi kesadaran
kesegaran reference detail for threadkesimpulansaran	Detil referensi kesegaran
kesegaran reference form for threadkesimpulansaran	Formulir referensi kesegaran
klasifikasi fungsional	Klasifikasi fungsional
kode_pos	Kode Pos
konfigurasi	Konfigurasi
konfigurasi reference form for faselatihan	Formulir referensi konfigurasi
konfig_rekaman reference detail for faselatihan	Detil referensi konfig rekaman
konfig_rekaman reference form for faselatihan	Formulir referensi konfig rekaman
konjunctifa	Konjunctifa
konjunctifa reference detail for eye	Detil referensi konjunctifa
konjunctifa reference form for eye	Formulir referensi konjunctifa
konsul	Konsul
kosongkan bila anda adalah pasien baru, kemudian klik submit	Kosongkan bila Anda adalah pasien baru, kemudian klik submit
kosongkan jika tidak tahu	Kosongkan jika tidak tahu
kota	Kota
kota makassar	Kota Makassar
kota palopo	Kota Palopo
kota parepare	Kota Parepare
kristen katolik	Kristen Katolik
kristen protestan	Kristen Protestan
kunjungan pasien hari ini	Kunjungan pasien hari ini
lainnya	Lainnya
laki-laki	Laki-laki
lampung	Lampung
language detail	Detil bahasa
language form	Formulir bahasa
layanan	Layanan
list antrian cardio anak	Daftar antrian cardio anak
list antrian cardio dewasa	Daftar antrian cardio dewasa
list antrian treadmill	Daftar antrian treadmill
list antrian vascular	Daftar antrian vascular
list bagian	Daftar bagian
lists cardio anak	Daftar cardio anak
lists cardio anak's patients	Daftar pasien cardio anak
lists cardio dewasa	Daftar cardio dewasa
lists cardio dewasa's patients	Daftar pasien cardio dewasa
liver reference detail for abdomen	Detil referensi liver
liver reference form for abdomen	Formulir referensi liver
localization reference detail for hearth	Detil referensi lokalisasi
localization reference form for hearth	Formulir referensi lokalisasi
login	Masuk
login_submit	Submit login
logout	Keluar
logout and redirected to home	Keluar dan diarahkan ke halaman utama
maluku	Maluku
maluku utara	Maluku Utara
medical record	Rekam medis
medical records of patient	Rekam medis pasien
mencari data pasien	Mencari data pasien
menu untuk menampilkan daftar group yang terdaftar	Menu untuk menampilkan grup yang terdaftar
menu untuk menampilkan daftar pengguna yang terdaftar	Menu untuk menampilkan pengguna yang terdaftar
menu untuk menampilkan detail group terdaftar yang terpilih	Menu untuk menampilkan detil grup terdaftar yang terpilih
menu untuk menampilkan detail pengguna terdaftar yang terpilih	Menu untuk menampilkan detil pengguna terdaftar yang terpilih
nama	Nama
nama_ayah	Nama Ayah
nama_ibu	Nama Ibu
nama_suami	Nama Suami
name	Nama
nanggroe aceh darussalam	Nanggroe Aceh Darussalam
new words	Kalimat baru
no	No.
nomor	Nomor
no_hp	No. HP
no_identitas	No. Identitas
no_tlp	No. Telp.
nusa tenggara barat	Nusa Tenggara Barat
nusa tenggara timur	Nusa Tenggara Timur
nutrient detail	Detil nutrisi
nutrient drop	Hapus Nutrisi
nutrient edit	Edit nutrisi
nutrient form	Formulir nutrisi
nutrient reference detail for present status	Detil referensi nutrisi
nutrient reference for present status	Referensi nutrisi
nutrient reference form for present status	Formulir referensi nutrisi
o	O
others reference detail for punggung	Detil referensi lainnya
others reference form for punggung	Formulir referensi lainnya
page	halaman
palpation reference detail for hearth	Detil referensi palpasi
palpation reference form for hearth	Formulir referensi palpasi
palpations reference detail for punggung	Detil referensi palpasi
palpations reference form for punggung	Formulir referensi palpasi
papua	Papua
papua barat	Papua Barat
pasien berkunjung	Pasien berkunjung
password	Sandi
patient	Pasien
patient detail	Detil pasien
patient get strnum info	Informasi nomor registrasi pasien
patient register	Registrasi pasien
patient update	Ubah pasien
pekerjaan	Pekerjaan
pekerjaan_ayah	Pekerjaan Ayah
pekerjaan_ibu	Pekerjaan Ibu
pekerjaan_suami	Pekerjaan Suami
pencarian dengan huruf awalan	Pencarian dengan huruf awal
pendaftaran pasien	Pendaftaran pasien
pendidikan	Pendidikan
pengguna	Pengguna
pengkajian	Pengkajian
penjalaran reference detail for hearth	Detil referensi penjalaran
penjalaran reference form for hearth	Formulir referensi penjalaran
perawatan	Perawatan
perawatan message	Pesan perawatan
percussion_bottom reference detail for hearth	Detil referensi perkusi bawah
percussion_bottom reference form for hearth	Formulir referensi perkusi bawah
percussion_left reference detail for hearth	Detil referensi perkusi kiri
percussion_left reference form for hearth	Formulir referensi perkusi kiri
percussion_right reference detail for hearth	Detil referensi perkusi kanan
percussion_right reference form for hearth	Formulir referensi perkusi kanan
percussion_top reference detail for hearth	Detil referensi perkusi atas
percussion_top reference form for hearth	Formulir referensi perkusi atas
perempuan	Perempuan
peristaltik_usus reference detail for abdomen	Detil referensi peristaltik usus
peristaltik_usus reference form for abdomen	Formulir referensi peristaltik usus
perkusi reference detail for abdomen	Detil referensi perkusi
perkusi reference form for abdomen	Formulir referensi perkusi
perubahan informasi pengguna	Perubahan informasi pengguna
perubahan sandi pengguna	Perubahan sandi pengguna
perubahan_gelombang	Perubahan gelombang
perubahan_gelombang reference detail for faselatihan	Detil referensi perubahan gelombang
perubahan_gelombang reference form for faselatihan	Formulir referensi perubahan gelombang
propinsi	Propinsi
protokol	Protokol
protokol reference detail for faselatihan	Detil referensi protokol
protokol reference form for faselatihan	Formulir referensi protokol
pulse rythm reference form for vitalsign	Formulir referensi ritme pulsa
pulse_rythm reference detail for vitalsign	Detil referensi ritme pulsa
pulse_rythm reference form for vitalsign	Formulir referensi ritme pulsa
punggung_bunyi_pernafasan	Bunyi pernafasan
punggung_bunyi_pernafasan drop	Hapus bunyi pernafasan
punggung_bunyi_pernafasan edit	Edit bunyi pernafasan
punggung_bunyi_pernafasan form	Formulir bunyi pernafasan
punggung_bunyi_tambahan	Bunyi tambahan
punggung_bunyi_tambahan drop	Hapus bunyi tambahan
punggung_bunyi_tambahan edit	Edit bunyi tambahan
punggung_bunyi_tambahan form	Formulir bunyi tambahan
punggung_inspections	Inspeksi punggung
punggung_inspections drop	Hapus inspeksi
punggung_inspections edit	Edit inspeksi
punggung_inspections form	Formulir inspeksi
punggung_others	Lainnya
punggung_others drop	Hapus lainnya
punggung_others edit	Edit lainnya
punggung_others form	Formulir lainnya
punggung_palpations	Palpasi
punggung_palpations drop	Hapus palpasi
punggung_palpations edit	Edit palpasi
punggung_palpations form	Formulir palpasi
pupil	Pupil
pupil reference detail for eye	Detil referensi pupil
pupil reference form for eye	Formulir referensi pupil
q interval	Q interval
qpatologi	Q Patologi
qpatologi reference detail for ekgqrs	Detil referensi QPatologi
qpatologi reference detail for ekgst	Detil referensi QPatologi
qpatologi reference form for ekgqrs	Formulir referensi QPatologi
qpatologi reference form for ekgst	Formulir referensi QPatologi
q_interval reference detail for fekg	Detil referensi Q interval
q_interval reference form for fekg	Formulir referensi Q interval
rambut	Rambut
rectal_touche reference detail for anusrectum	Detil referensi rectal touche
rectal_touche reference form for anusrectum	Formulir referensi rectal touche
redirect pengkajian	Pengalihan pengkajian
redirect perawatan's patients to it's items	Pengalihan pasien perawatan ke bagian-bagian
redirect to perawatans item	dialihkan ke bagian perawatan
redirecting pengkajian menus	Pengalihan menu pengkajian
reference information for all system	Informasi referensi untuk semua sistem 
referensi	Referensi
register patient into database	Registrasi pasien ke dalam database
registrasi pendaftaran pasien rawat inap	Registrasi pendaftaran pasien rawat inap
registrasi perawatan	Registrasi perawatan
relief reference detail for abdomen	Detil referensi relif
relief reference form for abdomen	Formulir referensi relif
reloading menus	Tampilkan ulang menu-menu
remove  risk_factor reference form for present status	Formulir penghapusan referensi faktor resiko
remove af reference form for holterref	Formulir penghapusan referensi AF
remove auscultation reference form for abdomen	Formulir penghapusan referensi auscultation
remove auscultation_kind reference form for hearth	Formulir penghapusan referensi jenis auscultation
remove auscultation_quality reference form for hearth	Formulir penghapusan referensi kualitas auscultation
remove auscultation_sound reference form for hearth	Formulir penghapusan referensi suara auscultation
remove axis reference form for ekgqrs	Formulir penghapusan referensi axis
remove bagian reference form	Formulir penghapusan referensi bagian
remove bunyi_pernafasan reference form for punggung	Formulir penghapusan referensi bunyi pernafasan
remove bunyi_tambahan reference form for punggung	Formulir penghapusan referensi bunyi tambahan
remove center reference form for abdomen	Formulir penghapusan referensi center
remove cornea reference form for eye	Formulir penghapusan referensi kornea
remove denyut_jantung reference form for fekg	Formulir penghapusan referensi denyut jantung
remove depresi reference form for ekgst	Formulir penghapusan referensi depresi
remove dihentikan reference form for faselatihan	Formulir penghapusan referensi dihentikan
remove durasi reference form for ekgqrs	Formulir penghapusan referensi durasi
remove durasi reference form for ekgst	Formulir penghapusan referensi durasi
remove expression reference form for headface	Formulir penghapusan referensi eksresi
remove fungsional reference form for threadkesimpulansaran	Formulir penghapusan referensi fungsional
remove gelombang p reference form for fekg	Formulir penghapusan referensi gelombang P
remove gerakan_dinding_perut reference form for abdomen	Formulir penghapusan referensi gerakan dinding perut
remove ginjal reference form for abdomen	Formulir penghapusan referensi ginjal
remove hair reference form for headface	Formulir penghapusan referensi rambut
remove heartblock reference form for holterref	Formulir penghapusan referensi heartblock
remove hepar reference form for abdomen	Formulir penghapusan referensi hati
remove illness_history reference form for present status	Formulir penghapusan referensi riwayat penyakit
remove inspection reference form for hearth	Formulir penghapusan referensi inspeksi
remove inspections reference form for anusrectum	Formulir penghapusan referensi inspeksi
remove inspections reference form for extermitas	Formulir penghapusan referensi inspeksi
remove inspections reference form for eye	Formulir penghapusan referensi inspeksi
remove inspections reference form for headface	Formulir penghapusan referensi inspeksi
remove inspections reference form for punggung	Formulir penghapusan referensi inspeksi
remove inspeksi_ginjal reference form for abdomen	Formulir penghapusan referensi inspeksi ginjal
remove intencity reference form for hearth	Formulir penghapusan referensi intensitas
remove irama reference form for fekg	Formulir penghapusan referensi irama
remove kelopak_mata reference form for eye	Formulir penghapusan referensi kelopak mata
remove kesadaran reference form for vitalsign	Formulir penghapusan referensi kesadaran
remove kesegaran reference form for threadkesimpulansaran	Formulir penghapusan referensi kesegaran
remove konfig_rekaman reference form for faselatihan	Formulir penghapusan referensi konfig rekaman
remove konjunctifa reference form for eye	Formulir penghapusan referensi konjunctifa
remove liver reference form for abdomen	Formulir penghapusan referensi liver
remove localization reference form for hearth	Formulir penghapusan referensi lokalisasi
remove nutrient reference form for present status	Formulir penghapusan referensi nutrisi
remove others reference form for punggung	Formulir penghapusan referensi lainnya
remove palpation reference form for hearth	Formulir penghapusan referensi palpasi
remove palpations reference form for punggung	Formulir penghapusan referensi palpasi
remove penjalaran reference form for hearth	Formulir penghapusan referensi penjalaran
remove percussion_bottom reference form for hearth	Formulir penghapusan referensi perkusi bawah
remove percussion_left reference form for hearth	Formulir penghapusan referensi perkusi kiri
remove percussion_right reference form for hearth	Formulir penghapusan referensi perkusi kanan
remove percussion_top reference form for hearth	Formulir penghapusan referensi perkusi atas
remove peristaltik_usus reference form for abdomen	Formulir penghapusan referensi peristaltik usus
remove perkusi reference form for abdomen	Formulir penghapusan referensi perkusi
remove perubahan_gelombang reference form for faselatihan	Formulir penghapusan referensi perubahan gelombang
remove protokol reference form for faselatihan	Formulir penghapusan referensi protokol
remove pulse_rythm reference form for vitalsign	Formulir penghapusan referensi ritme pulsa
remove pupil reference form for eye	Formulir penghapusan referensi pupil
remove qpatologi reference form for ekgqrs	Formulir penghapusan referensi QPatologi
remove qpatologi reference form for ekgst	Formulir penghapusan referensi QPatologi
remove q_interval reference form for fekg	Formulir penghapusan referensi Q interval
remove rectal_touche reference form for anusrectum	Formulir penghapusan referensi rectal touche
remove relief reference form for abdomen	Formulir penghapusan referensi relif
remove respon_jantung reference form for faselatihan	Formulir penghapusan referensi respon jantung
remove respon_jantung reference form for fekg	Formulir penghapusan referensi respon jantung
remove rlbs reference form for ekgqrs	Formulir penghapusan referensi iga
remove rlbs reference form for ekgst	Formulir penghapusan referensi iga
remove skin reference form for abdomen	Formulir penghapusan referensi kulit
remove soreness reference form for present status	Formulir penghapusan referensi nyeri
remove svt reference form for holterref	Formulir penghapusan referensi SVT
remove tekanandarah reference form for threadkesimpulansaran	Formulir penghapusan referensi tekanan darah
remove tekanan_bola_mata reference form for eye	Formulir penghapusan referensi tekanan bola mata
remove type reference form for vitalsign	Formulir penghapusan referensi tipe
remove ulib reference form for threadkesimpulansaran	Formulir penghapusan referensi ULJB
remove ves reference form for holterref	Formulir penghapusan referensi VES
rencana perawatan	Rencana perawatan
respon tekanan darah	Respon tekanan darah
respon tekanan darah reference form for threadkesimpulansaran	Formulir referensi respon tekanan darah
respon_jantung	respon jantung
respon_jantung reference detail for faselatihan	Detil referensi respon jantung
respon_jantung reference detail for fekg	Detil referensi respon jantung
respon_jantung reference form for faselatihan	Formulir referensi respon jantung
respon_jantung reference form for fekg	Formulir referensi respon jantung
rewrite_registry	Tulis ulang registry
riau	Riau
risk_factor drop	Hapus faktor resiko
risk_factor edit	Edit faktor resiko
risk_factor form	Formulir faktor resiko
risk_factor reference detail for present status	Detil referensi faktor resiko
risk_factor reference form for present status	Formulir referensi faktor resiko
riwayat kesehatan	Riwayat kesehatan
riwayat penyakit	Riwayat penyakit
rlbs	Iga
rlbs reference detail for ekgqrs	Detil referensi iga
rlbs reference detail for ekgst	Detil referensi iga
rlbs reference form for ekgqrs	Formulir referensi iga
rlbs reference form for ekgst	Formulir referensi iga
sandi	Sandi
sandi baru	Sandi baru
sandi konfirmasi	Sandi konfirmasi
sandi lama	Sandi lama
search	Cari
search cardio anak	Cari cardio anak
search cardio anak's patients	Cari pasien cardio anak
search cardio dewasa	Pencarian cardio dewasa
search cardio dewasa's patients	Cari pasien cardio dewasa
search ekg	Pencarian EKG
search ekg's patients	Cari pasien EKG
search holter	Pencarian holter
search holter's patients	Cari pasien holter
search perawatan	Pencarian perawatan
search perawatan's patients	Cari pasien perawatan
search treadmill	Pencarian treadmill
search treadmill's patients	Cari pasien treadmill
search vascular	Pencarian vascular
search vascular's patients	Cari pasien vascular
searching patient in database	Cari pasien dalam database
segala kegiatan dalam layanan rawat inap pasien	Segala kegiatan dalam layanan rawat inap pasien
selamat datang di cardiac center	Selamat Datang di Cardiac Center
silahkan login sebelum menggunakan aplikasi ini	Silahkan masuk sebelum menggunakan aplikasi ini
skin reference detail for abdomen	Detil referensi kulit
skin reference form for abdomen	Formulir referensi kulit
soreness drop	Hapus nyeri
soreness edit	Edit nyeri
soreness form	Formulir nyeri
soreness reference detail for present status	Detil referensi nyeri
soreness reference form for present status	Formulir referensi nyeri
status	Status
strnum	Nomor registrasi
submit	submit
submitted search cardio anak	Laksanakan pencarian cardio anak
submitted search cardio anak's patients	Laksanakan pencarian pasien cardio anak
submitted search cardio dewasa	Laksanakan pencarian cardio dewasa
submitted search cardio dewasa's patients	Laksanakan pencarian pasien cardio dewasa
submitted search ekg	Laksanakan pencarian EKG
submitted search ekg's patients	Laksanakan pencarian pasien EKG
submitted search holter	Laksanakan pencarian holter
submitted search holter's patients	Laksanakan pencarian pasien holter
submitted search perawatan	Laksanakan pencarian perawatan
submitted search perawatan's patients	Laksanakan pencarian pasien perawatan
submitted search treadmill	Laksanakan pencarian treadmill
submitted search treadmill's patients	Laksanakan pencarian pasien treadmill
submitted search vascular	Laksanakan pencarian vascular
submitted search vascular's patients	Laksanakan pencarian pasien vascular
submitting update patient's info execution	Laksanakan eksekusi perubahan informasi pasien
suku	Suku
sulawesi barat	Sulawesi Barat
sulawesi selatan	Sulawesi Selatan
sulawesi tengah	Sulawesi Tengah
sulawesi tenggara	Sulawesi Tenggara
sulawesi utara	Sulawesi Utara
sumatera barat	Sumatera Barat
sumatera selatan	Sumatera Selatan
sumatera utara	Sumatera Utara
svt	SVT
svt reference detail for holterref	Detil referensi SVT
svt reference form for holterref	Formulir referensi SVT
tekanan bola mata	Tekanan bola mata
tekanandarah reference detail for threadkesimpulansaran	Detil referensi tekanan darah
tekanandarah reference form for threadkesimpulansaran	Formulir referensi tekanan darah
tekanan_bola_mata reference detail for eye	Detil referensi tekanan bola mata
tekanan_bola_mata reference form for eye	Formulir referensi tekanan bola mata
tekanan_darah	Tekanan Darah
tgl_lahir	Tanggal Lahir
theme	Tema
threadkesimpulansaran_fungsional drop	Hapus fungsional
threadkesimpulansaran_fungsional edit	Edit fungsional
threadkesimpulansaran_fungsional form	Formulir fungsional
threadkesimpulansaran_kesegaran drop	Hapus kesegaran
threadkesimpulansaran_kesegaran edit	Edit kesegaran
threadkesimpulansaran_kesegaran form	Formulir kesegaran
threadkesimpulansaran_tekanandarah drop	Hapus tekanan darah
threadkesimpulansaran_tekanandarah edit	Edit tekanan darah
threadkesimpulansaran_tekanandarah form	Formulir tekanan darah
threadkesimpulansaran_ulib drop	Hapus ULJB
threadkesimpulansaran_ulib edit	Edit ULJB
threadkesimpulansaran_ulib form	Formulir ULJB
tidak kawin	Tidak Kawin
tinggi	Tinggi
tingkat kesegaran jasmani	Tingkat kesegaran jasmani
tipe tanda vital	Tipe tanda vital
tp_lahir	Tempat Lahir
translate	terjemahkan
translate new	Terjemahkan yang baru
translate new words into default language	Terjemahkan kalimat yang baru ke dalam bahasa utama
translate word into certain language	Terjemahkan kalimat ke dalam bahasa tertentu
translations	Terjemahan
treadmill	Treadmill
treadmillmessage	Pesan treadmill
type reference detail for vitalsign	Detil referensi tipe
type reference form for vitalsign	Formulir referensi tipe
ulib	ULJB
ulib reference detail for threadkesimpulansaran	Detil referensi ULJB
ulib reference form for threadkesimpulansaran	Formulir referensi ULJB
update	Ubah
updating patient's info	Ubah informasi pasien
user	Pengguna
user detail	Detil pengguna
user edit	Edit pengguna
user password	Sandi pengguna
user setings	Pengaturan pengguna
user settings	Pengaturan pengguna
user's password	Sandi pengguna
userid	ID Pengguna
username	Nama pengguna
usia	Usia
vascular echo-doppler	Echo doppler
vascularmessage	Pesan vascular
ves	VES
ves reference detail for holterref	Detil referensi VES
ves reference form for holterref	Formulir referensi VES
view login form to access authenticated menu	Tampilan formulir pintu masuk untuk mengakses menu yang diizinkan
vitalsign_kesadaran drop	Hapus kesadaran
vitalsign_kesadaran edit	Edit kesadaran
vitalsign_kesadaran form	Formulir kesadaran
vitalsign_pulse_rythm drop	Hapus ritme pulsa
vitalsign_pulse_rythm edit	Edit ritme pulsa
vitalsign_pulse_rythm form	Formulir ritme pulsa
vitalsign_type drop	Hapus tipe
vitalsign_type edit	Edit tipe
vitalsign_type form	Formulir tipe
words	Kalimat
words that translated in	Kalimat yang diterjemahkan ke dalam
