<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  thorax.php
 *  
 *  Created on Oct 4, 2009, 8:19:17 AM
 */

require_once MODULES_DIR . DS . 'thorax' . DS . 'thorax.class.inc';

if(!isset($thorax_config)){
    $thorax_config = new thoraxConfig();
} elseif(!$thorax_config instanceof thoraxConfig) {
    $thorax_config = new thoraxConfig();
}

require_once DBSTRINGS_DIR . DS . $thorax_config->rdbms . DS . 'dbquery.php';
if(!isset($thorax_query)){
    $thorax_query = new dbset();
} elseif(!$thorax_query instanceof dbset) {
    $thorax_query = new dbset();
}

if(!isset($thorax_exec)){
    $thorax_exec = new thoraxModule();
} elseif(!$thorax_exec instanceof thoraxModule) {
    $thorax_exec = new thoraxModule();
}
