<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  group.php
 *  
 *  Created on Sep 26, 2009, 10:30:55 AM
 */

require_once MODULES_DIR . DS . 'group' . DS . 'group.class.inc';

if(!isset($group_config)){
    $group_config = new groupConfig();
} elseif(!$group_config instanceof groupConfig) {
    $group_config = new groupConfig();
}

require_once DBSTRINGS_DIR . DS . $group_config->rdbms . DS . 'dbquery.php';
if(!isset($group_query)){
    $group_query = new dbset();
} elseif(!$group_query instanceof dbset) {
    $group_query = new dbset();
}

if(!isset($group_exec)){
    $group_exec = new groupModule();
} elseif(!$group_exec instanceof groupModule) {
    $group_exec = new groupModule();
}
