<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  diagnosa.php
 *  
 *  Created on Oct 4, 2009, 7:11:16 AM
 */

require_once MODULES_DIR . DS . 'diagnosa' . DS . 'diagnosa.class.inc';

if(!isset($diagnosa_config)){
    $diagnosa_config = new diagnosaConfig();
} elseif(!$diagnosa_config instanceof diagnosaConfig) {
    $diagnosa_config = new diagnosaConfig();
}

require_once DBSTRINGS_DIR . DS . $diagnosa_config->rdbms . DS . 'dbquery.php';
if(!isset($diagnosa_query)){
    $diagnosa_query = new dbset();
} elseif(!$diagnosa_query instanceof dbset) {
    $diagnosa_query = new dbset();
}

if(!isset($diagnosa_exec)){
    $diagnosa_exec = new diagnosaModule();
} elseif(!$diagnosa_exec instanceof diagnosaModule) {
    $diagnosa_exec = new diagnosaModule();
}
