<?php
/* 
 *  Copyright (c) 2009 Denic Wibowo<denicwibowo@gmail.com>.
 *  All rights reserved.
 *  
 *  This program is free software; you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the 
 *  Free Software Foundation; either version 2 of the License, or 
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along 
 *  with this program; if not, write to the Free Software Foundation, Inc., 
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *  
 *  ekg.php
 *  
 *  Created on Oct 3, 2009, 8:38:26 PM
 */

require_once MODULES_DIR . DS . 'ekg' . DS . 'ekg.class.inc';

if(!isset($ekg_config)){
    $ekg_config = new ekgConfig();
} elseif(!$ekg_config instanceof ekgConfig) {
    $ekg_config = new ekgConfig();
}

require_once DBSTRINGS_DIR . DS . $ekg_config->rdbms . DS . 'dbquery.php';
if(!isset($ekg_query)){
    $ekg_query = new dbset();
} elseif(!$ekg_query instanceof dbset) {
    $ekg_query = new dbset();
}

if(!isset($ekg_exec)){
    $ekg_exec = new ekgModule();
} elseif(!$ekg_exec instanceof ekgModule) {
    $ekg_exec = new ekgModule();
}
